### PR TITLE
Performed the asked changes in README.md

### PR DESCRIPTION
**Pull request by SPOCTONE**
linked with issue #27

### CODE REVIEW

**Comment by SPOCTONE** [comment]
P.S. in my opinion the image should've been aligned to the center... It would look better that way right?

**Comment by guyluz11** [comment]
The image is not centered 

image

**Comment by SPOCTONE** [comment]
Yep. that's what I was taking about. let me do it right now.

**Comment by SPOCTONE** [comment]
Sorry for the multiple commits 😅 Markdown is confusing.

**Comment by guyluz11** [comment]
Perfect 

Thanks @SPOCTONE

**Comment by guyluz11** [comment]
#27

**Comment by SPOCTONE** [comment]
No problem 🤠

**Pull request merged**
