### PR TITLE
added ru-KZ

### LINKED ISSUE #518: translation: ru-KZ
translation to the language ru-KZ

### PR DESCRIPTION
**Pull request by neocollege**
added ru-KZ translations
Fixes #518
Reference #428

### CODE REVIEW

**Comment by guyluz11** [comment]
Please respon pr to dev

**Comment by Utsav1999** [comment]
> added ru-KZ translations Fixes #428

Hello @neocollege ,

I saw that you have opened a new issue #518. So you should link that issue with your PR because you are solving that only. And mention #428 as a reference.

Thank you. Have a great day ahead ✌️

**Comment by neocollege** [comment]
> > added ru-KZ translations Fixes #428
> 
> Hello @neocollege ,
> 
> I saw that you have opened a new issue #518. So you should link that issue with your PR because you are solving that only. And mention #428 as a reference.
> 
> Thank you. Have a great day ahead ✌️ 

done, thanks!

**Comment by guyluz11** [comment]
Pr is still pointing to master branch
Screenshot_20221009_104420

**Comment by neocollege** [comment]
> Pr is still pointing to master branch Screenshot_20221009_104420

hey, changed it to dev

**Comment by guyluz11** [comment]
Thanks for the pr @neocollege and a happy Hacktoberfest :D

**Pull request merged**
