### PR TITLE
Resolved - rgbW light text out of bounds

### PR DESCRIPTION
**Pull request by chandansgowda**
I have wrapped the text widget with felxible and added textoverflow to clip in text style. I have attached images for long and short names.

long
short

### CODE REVIEW

**Comment by guyluz11** [comment]
Hi, can you change the pr to dev branch?

Thanks

**Comment by chandansgowda** [comment]
Hey @guyluz11,
I have changed the PR to dev branch.
Thanks

**Review by guyluz11 — APPROVED** [review]
Good

**Comment by guyluz11** [comment]
I have just opened a similar issue in the repo of the site, feel free to also take a look

https://github.com/CyBear-Jinni/CBJ_Site/issues/140

Thanks for the pr

**Pull request merged**
