### PR TITLE
Upgraded Package versions to latest compatible versions Fixes #580

### LINKED ISSUE #580: Update packages to the last version
Please update packages to the last version

### PR DESCRIPTION
**Pull request by omar1024**
Fixes #580

### CODE REVIEW

**Comment by guyluz11** [comment]
There are more packages that need to be updated, can you add them?

**Comment by omar1024** [comment]
> There are more packages that need to be updated, can you add them?

I didn't updated `auto_route_generator` to latest one because other packages were depended on this version

**Comment by guyluz11** [comment]
Is there any advantage to add fixes version to `build_runner`?

**Comment by guyluz11** [comment]
Cool
So we will add the version for that from now, thanks for the pr and a happy Hacktoberfest 😁

Feel free to star the project to show support ⭐

**Pull request merged**
