### PR TITLE
Add translation of Indonesia language

### PR DESCRIPTION
**Pull request by Iqrar99**
Add a translation for the Indonesian language as id-ID.json. ref #56

### CODE REVIEW

**Comment by guyluz11** [comment]
Looks good @Iqrar99 thank you.

**Comment by guyluz11** [comment]
If you would like to help us make the world a better place a star to the project will help.

Happy hacktoberfest :)

**Comment by Iqrar99** [comment]
> Looks good @Iqrar99 thank you.

You are welcome 😃

**Comment by guyluz11** [comment]
#58

**Pull request merged**
