### PR TITLE
Added required translations in hi-IN.json

### PR DESCRIPTION
**Pull request by ojninja16**

### CODE REVIEW

**Comment by guyluz11** [comment]
Hi @ojninja16 thanks for the pr.

It looks like your pr has conflicts, can you solve it please?

**Comment by ojninja16** [comment]
yeah sure....on it...

**Comment by ojninja16** [comment]
hi @guyluz11 i solved the conflicts please review......thanks

**Comment by guyluz11** [comment]
Thanks for the pr @ojninja16 
And a Happy Hacktoberfest 😁

**Pull request merged**
