### PR TITLE
style: Connect to Hub page UI updated

### PR DESCRIPTION
**Pull request by Manty-K**
Connect to Hub page UI updated
According to new moc

### CODE REVIEW

**Comment by guyluz11** [comment]
Please next time add a link to the issue in the pr
#625 

I have updated the project version and some packages and it seems it created conflicts.
Can you please solve them?

**Comment by guyluz11** [comment]
Looks nice 
image

If you click the `more` button you arrive at this page
image

Please make it look simular

**Comment by Manty-K** [comment]
Conflicts resolved for current implementation.
Now working on More Connections options

**Comment by Manty-K** [comment]
**More Connections Options** page UI updated
fixes #625

**Comment by guyluz11** [comment]
Thanks :)

**Pull request merged**
