### PR TITLE
fixed icons and sizes 

### PR DESCRIPTION
**Pull request by Mahich123**
Icons has been changed and increased their sizes . Let me know if anything need to change

### CODE REVIEW

**Comment by guyluz11** [comment]
Hi @Mahich123 that looks really good,

Can you replace a GitHub icon that is not transparent in the middle? 
I can't see the icon on my black GitHub background. 
image

**Comment by guyluz11** [comment]
> As the logo is black and you using dark mode that's why those colors are mixing and showing transparent . To prevent we can use different color logo . As shown bellow :
> 
> https://seeklogo.com/images/G/github-colored-logo-FDDF6EB1F0-seeklogo.com.png

Yep this one is good.

**Comment by Mahich123** [comment]
@guyluz11  Fixed GitHub icon visibility you can check it now .

**Comment by Mahich123** [comment]
**Happy Hacktoberfest** 😊

**Pull request merged**
