### PR TITLE
fix warnings

### PR DESCRIPTION
**Pull request by ShishirRijal**
# Description
Fixed the warnings throughout the projects. However some implementations are to yet to be implemented, so they are just ignore for now. Otherwise, everything has been taken care of. 

Issue: #667 

# Snap
Screenshot 2023-10-21 at 9 01 00 AM

### CODE REVIEW

**Comment by guyluz11** [comment]
Pr should be from and to dev branch, did you forked dev?

**Comment by ShishirRijal** [comment]
I actually worked on the master branch. I will send a PR to the Dev branch. Should it be from the Dev too? I mean I fixed issues on master.

**Comment by ShishirRijal** [comment]
I've created a new PR from dev to dev.

**Comment by guyluz11** [comment]
Closing

**Pull request closed without merging**
