### PR TITLE
Implemented country code autofill in Tuya sign in

### PR DESCRIPTION
**Pull request by Ashwith25**
Fix for issue #318

### CODE REVIEW

**Comment by guyluz11** [comment]
Hi @Ashwith25 

On the package page https://pub.dev/packages/geocoding written that `compileSdkVersion 30` is needed but the current one is `29`.
Also this package support only android and IOS, will it crash for other environment or will just stay empty?.
Found google geocoding https://pub.dev/packages/google_geocoding which support more os's, what made you choose one over the other (if it requires google API then we will not use it).

If location permission is not granted do we catch the error?, the field should remain empty.

I see that you used `setState`, we are not using the default state management and moved to work with [bloc](https://pub.dev/packages/bloc), I will be happy to sit with you and show you how to use it instead of  `setState`.

**Comment by guyluz11** [comment]
Just ping me on the discord server and I will join the voice chat.

**Comment by Ashwith25** [comment]
I won't be available for few days. So if the feature is important to be implemented now, you may unassign me and assign this to someone else.
Sorry and thank you for the opportunity

**Comment by guyluz11** [comment]
There is no pressure with this feature so I will leave it on you for now. 
Thanks for letting me know.

**Comment by guyluz11** [comment]
Closing this pr, as I said in the issue, we stopped supporting Tuya integration for now (API got changed).

Thanks for taking the time to create the pr.

**Pull request closed without merging**
