### PR TITLE
added responsive layout for add devices page

### PR DESCRIPTION
**Pull request by SankethBK**

### CODE REVIEW

**Comment by SankethBK** [comment]
@guyluz11 i have intentionally added longer names for devices in demo, so that they take entire row and it would be easier for testing, will remove it before merging.

**Review by guyluz11 — APPROVED** [review]
Yep it is ok

**Comment by SankethBK** [comment]
@guyluz11 getting this error when i click on Done button. I tested it without my code, still getting same error

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: "Encountered a ValueFailure at an unrecoverable point. Terminating. Failure was: RoomFailure<String>.empty(failedValue: )"
#0      ValueObjectRooms.getOrCrash.<anonymous closure> (package:cybear_jinni/domain/room/value_objects_room.dart:17:30)
#1      Left.fold (package:dartz/src/either.dart:191:63)
#2      ValueObjectRooms.getOrCrash (package:cybear_jinni/domain/room/value_objects_room.dart:17:18)
#3      RoomSignInFormBloc._changeRoomDevices (package:cybear_jinni/application/room/create_new_room_form/room_sign_in_form_bloc.dart:71:54)
#4      Bloc.on.<anonymous closure>.handleEvent (package:bloc/src/bloc.dart:226:26)
#5      Bloc.on.<anonymous closure> (package:bloc/src/bloc.dart:235:9)
#6      _MapStream._handleData (dart:async/stream_pipe.dart:213:31)
#7      _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
#8      _RootZone.runUnaryGuarded (dart:async/zone.dart:1586:10)
#9      CastStreamSubscription._onData (dart:_internal/async_cast.dart:85:11)
#10     _RootZone.runUnaryGuarded (dart:async/zone.dart:1586:10)
#11     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#12     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#13     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
#14     _WhereStream._handleData (dart:async/stream_pipe.dart:195:12)
#15     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
#16     _RootZone.runUnaryGuarded (dart:async/zone.dart:1586:10)
#17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#18     _DelayedData.perform (dart:async/stream_impl.dart:515:14)
#19     _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)
#20     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591:7)
#21     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method showToast on channel PonnamKarthik/fluttertoast)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:294:7)
<asynchronous suspension>
#1      Fluttertoast.showToast (package:fluttertoast/fluttertoast.dart:100:17)
<asynchronous suspension>
```

**Comment by SankethBK** [comment]
Apart from that, all changes are done

**Comment by guyluz11** [comment]
On what platform are you testing?, If I remember correctly I got the same one while running on Linux but not on my Android phone

**Comment by SankethBK** [comment]
I guess it should go away after restarting the project. I was trying on Android emulator. https://stackoverflow.com/questions/62286575/how-to-solve-no-implementation-found-for-method-showtoast-in-flutter

**Comment by guyluz11** [comment]
> I guess it should go away after restarting the project. I was trying on Android emulator. https://stackoverflow.com/questions/62286575/how-to-solve-no-implementation-found-for-method-showtoast-in-flutter

If you look closely one of the answers in the link is mine 😂

**Pull request merged**
