### PR TITLE
Add PL translation

### PR DESCRIPTION
**Pull request by kat-kan**
Hello, I'm back with changed branch name

### CODE REVIEW

**Comment by guyluz11** [comment]
Not sure why it is crushing :(, will try to find a time to take a look at this.

**Comment by kat-kan** [comment]
The file should be fine...just checked with https://jsonformatter.curiousconcept.com/# and says it's valid
Maybe some Polish alphabet letters could cause a crash?

**Comment by guyluz11** [comment]
Tested with the text localy using the command 
`find . -name "*.dart" ! -path '*/gen/*' | tr '\n' ' ' | xargs dart format`
And it does not have any problems so "Polish alphabet letters could cause a crash?" no.

Did you create your branch from the updated dev?

**Comment by guyluz11** [comment]
I think I have found it, you created your fork from the master branch and not from dev "Main Branch Formatting C".
It should work but it seems that it has a problem with it.

Can you create fork from dev and create the pr?

I have created a pr using your text and it is passing 
https://github.com/CyBear-Jinni/cbj_app/pull/459

**Comment by kat-kan** [comment]
@guyluz11 can you please add "invalid" label? The translation was added by someone else.

**Pull request closed without merging**
