### PR TITLE
Adding  en-SG Translation

### PR DESCRIPTION
**Pull request by nabeel001**
I have added the en-SG translation.

### CODE REVIEW

**Comment by guyluz11** [comment]
> I have added the en-SG translation.

You have added both en-pk and en-sg in that pr.

Do you want to split it into two different pr?, I am fine either way

**Comment by nabeel001** [comment]
yes i would like to split them

**Comment by nabeel001** [comment]
I was expecting it to create two separate prs but i dont know how it ended up as a single pr

**Comment by nabeel001** [comment]
will send a fresh pr

**Pull request closed without merging**
