### PR TITLE
Adding Hebrew translation (only 2 words was not understandable)

### PR DESCRIPTION
**Pull request by Tamir198**

### CODE REVIEW

**Comment by guyluz11** [comment]
Both name `Name:_` and `Room:_` can be found in this image :

**Comment by Tamir198** [comment]
> Both name `Name:_` and `Room:_` can be found in this image :
> 

Could you give me an example of how I should fill the Name and room object? So I will stay consistence with the English translate

**Comment by Tamir198** [comment]
> Both name `Name:_` and `Room:_` can be found in this image :
> 

And one more thing, as I wrote before but maybe it didn't got your attention:

Could you explain what do you want to tell the user by "Conditioner", "Scene_Settings_Page"
 It is not so clear and I don't want to make mistakes

**Comment by guyluz11** [comment]
The `name` is the name of the device that you see.
The `room` is the name of the room that the device is located in.

`Conditioner` should be changed to `Air Conditioner` as I see that it is not explains itself well enough

`Scene` is one button that do a lot of predefined actions with one press.
So the  `Scene_Settings_Page` is the setting page for it, place where you create your own scenes deleted them and change their names and configurations .

**Comment by guyluz11** [comment]
@Tamir198 
Thanks for the pull request

**Comment by guyluz11** [comment]
#56

**Pull request merged**
