### PR TITLE
Added en-PR.json

### PR DESCRIPTION
**Pull request by adityar224**

### CODE REVIEW

**Comment by guyluz11** [comment]
Hi @adityar224 thanks for the pr

it looks like it includes more changes that what you have intended for

This pr change the README.md as well as en-SG.json.

Please fix that

**Review by adityar224 — COMMENTED** [review]
checked

**Comment by adityar224** [comment]
@guyluz11 Sorry for the trouble.. Messed up a little bit here. But I've removed the other changes now

**Comment by guyluz11** [comment]
Thanks for the pr @adityar224 

And happy Hacktoberfest :D

**Pull request merged**
