### PR TITLE
Added Divehi (Maldivian) translations.

### PR DESCRIPTION
**Pull request by rameshwaghmare123**

### CODE REVIEW

**Comment by guyluz11** [comment]
Hi, I am sorry but I can't find your language under android supported languages, at list not in the form `dv-mv`.

My sources are from here
https://lingohub.com/developers/supported-locales/language-designators-with-regions
or from here
 https://stackoverflow.com/questions/7973023/what-is-the-list-of-supported-languages-locales-on-android

**Comment by guyluz11** [comment]
Ok, I have also found it in another source.

Can you change pr to dev branch?
Thanks

**Comment by rameshwaghmare123** [comment]
Moved to dev branch

**Comment by guyluz11** [comment]
Thanks for the pr @rameshwaghmare123  and a happy Hacktoberfest 😁

Feel free to star the project to show support ⭐

**Pull request merged**
