### PR TITLE
:bricks: ci: ignore `injection.config.dart` file

### LINKED ISSUE #534: Ignore file in git action dart format #
Same as in this issue in the Hub repo https://github.com/CyBear-Jinni/cbj_hub/issues/182 we would like to ignore `injection.config.dart` file from the git action format.
 
So just add to this:

https://github.com/CyBear-Jinni/cbj_app/blob/426d29b431ea514c70506a15f8d5e02cfebc9d30/.github/workflows/format.yml#L20

this part (inspiration https://github.com/CyBear-Jinni/cbj_hub/pull/202/files):
`! -name 'injection.config.dart'`

### PR DESCRIPTION
**Pull request by AlgyJr**
Closes #534

### CODE REVIEW

**Comment by guyluz11** [comment]
Please change pr to dev branch

**Comment by AlgyJr** [comment]
> Please change pr to dev branch

Done @guyluz11

**Comment by guyluz11** [comment]
Thanks for the pr @AlgyJr and a happy Hacktoberfest 😁

Feel free to star ⭐ the project

**Comment by AlgyJr** [comment]
> Thanks for the pr @AlgyJr and a happy Hacktoberfest 😁
> 
> 
> 
> Feel free to star ⭐ the project 

Thanks for the opportunity❤️

**Pull request merged**
