### PR TITLE
[Refactor] Fixed folder to dev branch 🎨 

### PR DESCRIPTION
**Pull request by sohan-k**
Fixed folder to dev branch as requested taking all the files to the root folder :)

### CODE REVIEW

**Comment by sohan-k** [comment]
@guyluz11  please merge this before merging other prs as it is causing conflicts.

**Comment by guyluz11** [comment]
> @guyluz11 please merge this before merging other prs as it is causing conflicts.

I prefer to do it after and there will only be one change here as it is simpler.
I'll send another message after closing all the big wave of the prs and then I'll be happy if you resolve the conflicts and will marge it straight.

Sorry for the extra work

**Comment by guyluz11** [comment]
Ok finished all the pull request review.

You can resolve conflicts now.

**Comment by sohan-k** [comment]
Finished it @guyluz11

**Comment by sohan-k** [comment]
Hey @guyluz11 , does Dart CI is having a configuration problem or anything else to cause the All checks error

**Comment by guyluz11** [comment]
Thanks for the quick response. 

Will merge it not

**Comment by guyluz11** [comment]
> Hey @guyluz11 , does Dart CI is having a configuration problem or anything else to cause the All checks error

Dart CI is dependent on the location of the project, I will create pull request to fix this to the new folder structure.

**Pull request merged**
