### PR TITLE
Create en-HT.json

### PR DESCRIPTION
**Pull request by prabhleenn**

### CODE REVIEW

**Comment by prabhleenn** [comment]
hey! I just added the en-HT translation.
I opened PR #590 and changed the file
Thanks for the opportunity.

**Comment by prabhleenn** [comment]
hey! I just added the en-HT translation.
I opened PR https://github.com/CyBear-Jinni/cbj_app/pull/590 and changed the file
Thanks for the opportunit

**Comment by guyluz11** [comment]
Wrong file location please fix

**Comment by guyluz11** [comment]
Closing this pr as there is a new one with the correct path of file

**Pull request closed without merging**
