### PR TITLE
Dependency Updated to the latest Version

### PR DESCRIPTION
**Pull request by UtkarshDeoli**
**-- 17 the dependencies are updated without errors--**

**-- Two left because they give error when updated , they are as following --**
        1. device_info_plus: ^4.0.2 --> device_info_plus: ^5.0.0
        2. freezed: ^2.1.0+1 --> freezed: ^2.1.1

### CODE REVIEW

**Comment by guyluz11** [comment]
Dart ci not passing

I think it's because your repo is based on Master branch.

Can you make a new Branch based on dev and then commit your needed changes?

**Comment by guyluz11** [comment]
CI does not pass
Screenshot_20221006-005241_Firefox

Increase dart sdk to 2.18.1

**Comment by guyluz11** [comment]
Thanks for the pr and a happy Hacktoberfest @UtkarshDeoli 🎁

**Comment by UtkarshDeoli** [comment]
fixes #482

**Pull request merged**
