### PR TITLE
Flutter ci added

### LINKED ISSUE #681: Add Flutter Ci
Proposing the inclusion of a Flutter CI workflow in our CyBear-Jinni repository. This implementation will facilitate the automatic testing and deployment of our Flutter application, enhancing the stability and reliability of our development process. This addition carries significant value, streamlining our workflow, and elevating the overall quality of our application. Kindly consider assigning this task to me for implementation if you share this perspective. Your support is greatly appreciated.

### PR DESCRIPTION
**Pull request by andoriyaprashant**
## Changes -

- Flutter Ci Added
- For branches:
      - master
      - dev

- pull request branches:
      - master
      - dev

### CODE REVIEW

**Comment by guyluz11** [comment]
How is it different from the current ci?, and if there is new features why not adding it to the current one
https://github.com/CyBear-Jinni/cbj_app/tree/master/.github/workflows

**Comment by andoriyaprashant** [comment]
Hello @guyluz11 The "Dart CI" workflow is focused on testing Dart code and allows you to select the Flutter channel and version as environment variables. The "Flutter CI" workflow, on the other hand, is primarily focused on Flutter, and it not only tests the code but also builds an APK and archives it as an artifact and If you want me to make changes in this, please let me know.

**Comment by guyluz11** [comment]
APK archive could be good

Planning a massive change to the repo, I think I'll put it in after the change

**Comment by guyluz11** [comment]
Thanks for the PR

**Pull request merged**
