### PR TITLE
add new translation file Malay (Malaysia)

### PR DESCRIPTION
**Pull request by mohfirdaus**

### CODE REVIEW

**Comment by mohfirdaus** [comment]
PR for hacktoberfest :)

**Comment by guyluz11** [comment]
Hi @mohfirdaus 
It looks like the file you have added is empty

**Comment by mohfirdaus** [comment]
> Hi @mohfirdaus It looks like the file you have added is empty

Updated :)

**Comment by guyluz11** [comment]
Thanks for the pr

and happy Hacktoberfest 😁

**Pull request merged**
